version: "3"
services:
  db:
    container_name: db_container
    image: postgres:14.3-bullseye
    env_file:
      - db/postgresql/.env
    ports:
      - 5430:5432
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
    driver: local