[sources]
cyberleninka = "https://cyberleninka.ru/article"
gtmarket = "https://gtmarket.ru/encyclopedia"
philosophy = "https://www.philosophy.ru/library"
journals = "https://iphras.ru/journals.html"
elibrary = "https://elibrary.ru"
habr = "https://habr.ru"
