# Generated by Django 4.1.3 on 2022-12-01 20:43

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DemoCyberleninka",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("cyberleninka_id", models.CharField(max_length=456)),
                ("title", models.CharField(max_length=400, verbose_name="Название")),
                ("authors", models.CharField(max_length=400, verbose_name="Авторы")),
                ("publication_year", models.IntegerField(verbose_name="Год публикации")),
                ("science_magazine_name", models.CharField(max_length=400, verbose_name="Название научного журнала")),
                ("science_magazine_url", models.URLField(max_length=500, verbose_name="Ссылка на научный журнал")),
                ("annotation", models.TextField(verbose_name="Аннотация")),
                ("annotation_en", models.TextField(verbose_name="Аннотация en")),
                ("article_text", models.TextField(verbose_name="Текст статьи")),
                ("field_of_sciences", models.CharField(max_length=600, verbose_name="Область науки")),
                ("tags", models.CharField(max_length=1000, verbose_name="Теги")),
                ("keywords", models.CharField(max_length=1000, verbose_name="Теги")),
                ("similar_topics", models.TextField(verbose_name="Похожие темы")),
                ("source_url", models.URLField(max_length=500, verbose_name="Ссылка на статью")),
                ("pdf_url", models.URLField(max_length=500, verbose_name="Ссылка на pdf")),
            ],
            options={
                "verbose_name": "Демоверсия КиберЛенинка",
                "verbose_name_plural": "Демоверсия КиберЛенинка",
                "db_table": "demo_cyberleninka",
            },
        ),
        migrations.AddConstraint(
            model_name="democyberleninka",
            constraint=models.UniqueConstraint(fields=("cyberleninka_id",), name="cyberleninka_id_pkey"),
        ),
    ]
